# frozen_string_literal: true

require "spec_helper"
require "fileutils"
require "tmpdir"
require "stringio"

# ---------------------------------------------------------------------------
# Railties must be loaded before rails/generators is required.
# Add `gem "railties"` to your Gemfile's :test group if not already present.
# ---------------------------------------------------------------------------
require "rails/generators"
require "rails/generators/base"

# ---------------------------------------------------------------------------
# Minimal Rails stubs so the generator can load and run without a full app.
# ---------------------------------------------------------------------------
unless defined?(Rails)
  module Rails
    def self.root = Pathname.new(Dir.pwd)
  end
end

# Stub Rails.application.class.module_parent_name used in step_project_info
unless Rails.respond_to?(:application) && Rails.application
  module Rails
    FakeApp     = Struct.new(:class)
    FakeAppClass = Struct.new(:module_parent_name)

    def self.application
      @application ||= FakeApp.new(FakeAppClass.new("TestApp"))
    end
  end
end

# ---------------------------------------------------------------------------
# Now load the generator under test
# ---------------------------------------------------------------------------
require "generators/respondo/install/install_generator"

RSpec.describe Respondo::Generators::InstallGenerator do

  # -------------------------------------------------------------------------
  # Helpers
  # -------------------------------------------------------------------------

  # Swap $stdin / $stdout around the block, restore in ensure.
  def with_io(input_str)
    old_in  = $stdin
    old_out = $stdout
    $stdin  = StringIO.new(input_str)
    $stdout = StringIO.new
    yield
  ensure
    $stdin  = old_in
    $stdout = old_out
  end

  # Run the generator, silently swallowing all output.
  def run_generator(*answers, dest:)
    input = answers.join("\n") + "\n"
    with_io(input) do
      gen = described_class.new([], {}, destination_root: dest)
      gen.run_interactive_setup
    end
  end

  # Run and return the captured terminal output string.
  def capture_run(*answers, dest:)
    old_in  = $stdin
    old_out = $stdout
    captured = StringIO.new
    $stdin   = StringIO.new(answers.join("\n") + "\n")
    $stdout  = captured

    gen = described_class.new([], {}, destination_root: dest)
    gen.run_interactive_setup

    captured.string
  ensure
    $stdin  = old_in
    $stdout = old_out
  end

  def initializer_path(dest)
    File.join(dest, "config", "initializers", "respondo.rb")
  end

  def initializer_content(dest)
    File.read(initializer_path(dest))
  end

  # Answer sequence — matches the generator's exact prompt order:
  #   1. ready?           y
  #   2. project name     MyApp
  #   3. api version      v2
  #   4. success message  OK
  #   5. error message    Oops
  #   6. request_id?      y
  #   7. camelize?        y
  #   8. add meta?        n
  #   9. serializer?      n
  HAPPY_ANSWERS = %w[y MyApp v2 OK Oops y y n n].freeze

  # -------------------------------------------------------------------------
  # Skip path
  # -------------------------------------------------------------------------

  describe "when user declines setup" do
    let(:dest) { Dir.mktmpdir("respondo_skip_") }
    after      { FileUtils.rm_rf(dest) }

    it "does not create the initializer file" do
      run_generator("n", dest: dest)
      expect(File.exist?(initializer_path(dest))).to be false
    end

    it "prints the skip message with the re-run hint" do
      output = capture_run("n", dest: dest)
      expect(output).to include("Skipped")
      expect(output).to include("rails generate respondo:install")
    end
  end

  # -------------------------------------------------------------------------
  # Happy path — file creation
  # -------------------------------------------------------------------------

  describe "happy path" do
    let(:dest)    { Dir.mktmpdir("respondo_happy_") }
    let(:content) { initializer_content(dest) }
    after         { FileUtils.rm_rf(dest) }

    before { run_generator(*HAPPY_ANSWERS, dest: dest) }

    it "creates config/initializers/respondo.rb" do
      expect(File.exist?(initializer_path(dest))).to be true
    end

    it "starts with the frozen string literal comment" do
      expect(content).to start_with("# frozen_string_literal: true")
    end

    it "writes the project name in the header" do
      expect(content).to include("# Respondo initializer — MyApp")
    end

    it "writes the generator origin comment" do
      expect(content).to include("# Generated by: rails generate respondo:install")
    end

    it "writes the Respondo version" do
      expect(content).to include("# Respondo version: #{Respondo::VERSION}")
    end

    it "wraps config in Respondo.configure block" do
      expect(content).to include("Respondo.configure do |config|")
      expect(content).to include("end")
    end

    it "writes the success message" do
      expect(content).to include('config.default_success_message = "OK"')
    end

    it "writes the error message" do
      expect(content).to include('config.default_error_message   = "Oops"')
    end

    it "writes include_request_id = true" do
      expect(content).to include("config.include_request_id = true")
    end

    it "writes camelize_keys = true" do
      expect(content).to include("config.camelize_keys = true")
    end

    it "writes api_version into default_meta" do
      expect(content).to include('api_version: "v2"')
    end
  end

  # -------------------------------------------------------------------------
  # Default values — blank Enter on every prompt
  # -------------------------------------------------------------------------

  describe "default values" do
    let(:dest)    { Dir.mktmpdir("respondo_defaults_") }
    let(:content) { initializer_content(dest) }
    after         { FileUtils.rm_rf(dest) }

    # ready=y, then blank for: name, version, success, error, n for rest
    before { run_generator("y", "", "", "", "", "n", "n", "n", "n", dest: dest) }

    it "defaults success message to Success" do
      expect(content).to include('config.default_success_message = "Success"')
    end

    it "defaults error message to An error occurred" do
      expect(content).to include('config.default_error_message   = "An error occurred"')
    end

    it "defaults api_version to v1" do
      expect(content).to include('api_version: "v1"')
    end

    it "defaults include_request_id to false" do
      expect(content).to include("config.include_request_id = false")
    end

    it "defaults camelize_keys to false" do
      expect(content).to include("config.camelize_keys = false")
    end
  end

  # -------------------------------------------------------------------------
  # Global meta fields
  # -------------------------------------------------------------------------

  describe "global meta fields" do
    let(:dest) { Dir.mktmpdir("respondo_meta_") }
    after      { FileUtils.rm_rf(dest) }

    context "when user adds meta fields" do
      before do
        run_generator(
          "y",               # ready
          "MetaApp", "v1",   # project, version
          "OK", "Err",       # success, error messages
          "n", "n",          # request_id, camelize
          "y",               # add meta?
          "platform=mobile", # first pair
          "env=production",  # second pair
          "",                # blank — stop
          "n",               # serializer
          dest: dest
        )
      end

      it "writes platform into default_meta" do
        expect(initializer_content(dest)).to include('platform: "mobile"')
      end

      it "writes env into default_meta" do
        expect(initializer_content(dest)).to include('env: "production"')
      end

      it "still writes api_version into default_meta" do
        expect(initializer_content(dest)).to include('api_version: "v1"')
      end
    end

    context "when user skips meta fields" do
      before { run_generator("y", "App", "v1", "OK", "Err", "n", "n", "n", "n", dest: dest) }

      it "only includes api_version in default_meta" do
        expect(initializer_content(dest)).to include('api_version: "v1"')
      end

      it "does not include any other meta keys" do
        expect(initializer_content(dest)).not_to match(/platform|env:/)
      end
    end

    context "when user enters a badly-formatted line (no = sign)" do
      # Replace the lazy `let(:output)` with an eager before + instance variable
      before do
        @output = capture_run(
          "y", "App", "v1", "OK", "Err", "n", "n",
          "y",
          "badline",
          "key=val",
          "",
          "n",
          dest: dest
        )
      end

      it "shows the format warning" do
        expect(@output).to include("Use key=value format")
      end

      it "still writes the valid pair that came after" do
        expect(initializer_content(dest)).to include('key: "val"')
      end
    end
  end

  # -------------------------------------------------------------------------
  # Custom serializer stub
  # -------------------------------------------------------------------------

  describe "custom serializer stub" do
    let(:dest) { Dir.mktmpdir("respondo_ser_") }
    after      { FileUtils.rm_rf(dest) }

    context "when user opts in" do
      before { run_generator("y", "App", "v1", "OK", "Err", "n", "n", "n", "y", dest: dest) }

      it "writes a commented serializer config line" do
        expect(initializer_content(dest)).to include("config.serializer")
      end

      it "includes a usage example" do
        expect(initializer_content(dest)).to include("MySerializer")
      end
    end

    context "when user opts out" do
      before { run_generator("y", "App", "v1", "OK", "Err", "n", "n", "n", "n", dest: dest) }

      it "does not write any serializer line" do
        expect(initializer_content(dest)).not_to include("config.serializer")
      end
    end
  end

  # -------------------------------------------------------------------------
  # Terminal output
  # -------------------------------------------------------------------------

  describe "terminal output" do
    let(:dest)   { Dir.mktmpdir("respondo_out_") }
    let(:output) { capture_run(*HAPPY_ANSWERS, dest: dest) }
    after        { FileUtils.rm_rf(dest) }

    it "prints the ASCII logo" do
      expect(output).to include("██")
    end

    it "prints the Respondo version in the logo" do
      expect(output).to include(Respondo::VERSION)
    end

    it "prints Configuration Summary exactly once" do
      expect(output.scan("Configuration Summary").size).to eq(1)
    end

    it "confirms the file was created with a checkmark" do
      expect(output).to include("✅")
      expect(output).to include("config/initializers/respondo.rb")
    end

    it "prints the done banner" do
      expect(output).to include("🎉")
      expect(output).to include("Respondo is ready!")
    end

    it "shows every section header" do
      [
        "Project Info",
        "Response Messages",
        "Request ID",
        "Key Format",
        "Global Meta Fields",
        "Custom Serializer"
      ].each { |h| expect(output).to include(h) }
    end
  end

  # -------------------------------------------------------------------------
  # Directory handling
  # -------------------------------------------------------------------------

  describe "directory handling" do
    let(:dest) { Dir.mktmpdir("respondo_dirs_") }
    after      { FileUtils.rm_rf(dest) }

    it "creates config/initializers/ when it does not yet exist" do
      run_generator(*HAPPY_ANSWERS, dest: dest)
      expect(Dir.exist?(File.join(dest, "config", "initializers"))).to be true
    end
  end

  # -------------------------------------------------------------------------
  # Idempotency
  # -------------------------------------------------------------------------

  describe "re-running the generator" do
    let(:dest) { Dir.mktmpdir("respondo_rerun_") }
    after      { FileUtils.rm_rf(dest) }

    it "overwrites the existing initializer without error" do
      run_generator(*HAPPY_ANSWERS, dest: dest)
      run_generator("y", "NewApp", "v3", "Great", "Bad", "n", "n", "n", "n", dest: dest)

      content = initializer_content(dest)
      expect(content).to include("# Respondo initializer — NewApp")
      expect(content).to include('api_version: "v3"')
      expect(content).not_to include("MyApp")
    end
  end
end